/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/game': {
    /** Get Current Available Games */
    get: operations['GetGames']
  }
  '/api/v1/game/player/info': {
    /** Get Player Detailed Info */
    get: operations['GetGamePlayerInfo']
  }
  '/api/v1/game/player/binding': {
    /**
     * Get Player Binding
     * @description Get the player's binding (Skland ID <-> Game ID) info
     */
    get: operations['GetGamePlayerBinding']
  }
  '/api/v1/user/auth/generate_cred_by_code': {
    /**
     * 通过鹰角网络通行证 OAuth2 授权码（Authorization Code）生成森空岛用户的登录凭证
     * @description 仅有获得内测资格的用户才可以生成登录凭证。如果该用户没有获得内测资格，则会返回 403 Forbidden。
     */
    post: operations['GenerateCredByCode']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    GetGamePlayerInfoResponseData: {
      /**
       * @description Timestamp in seconds
       * @example 1554105600
       */
      currentTs: number
      /**
       * ShowConfig
       * @description User preferences of the "show" page options.
       */
      showConfig: {
        /**
         * @description Current set value of the user preference "向其他用户展示我的干员".
         * @default true
         */
        charSwitch: boolean
        /**
         * @description Current set value of the user preference "向其他用户展示我的服装".
         * @default true
         */
        skinSwitch: boolean
        /**
         * @description Current set value of the user preference "向其他用户展示我的战绩".
         * @default true
         */
        standingsSwitch: boolean
      }
      /**
       * Status
       * @description User profile and status
       */
      status: {
        /**
         * Format: integer
         * @description In-game ID. Also found at the home page of the game, located at the left of the screen.
         */
        uid: string
        /** @description In-game nickname. Also found at the home page of the game, located at the left of the screen. */
        name: string
        /** @description Current level of the user. Maximum level is 120. */
        level: number
        /** Avatar */
        avatar: {
          /** @enum {string} */
          type: 'ICON'
          /**
           * @description In-game avatar ID.
           * @example avatar_special_06
           */
          id: string
        }
        /**
         * @description Timestamp (in seconds) of the in-game account creation time.
         * @example 1584537600
         */
        registerTs: number
        /**
         * @description Current progress of the main story. Value is a stageId string.
         * @example main_01-01
         */
        mainStageProgress: string
        /**
         * Secretary
         * @description User's secretary (助理).
         */
        secretary: {
          /**
           * @description In-game character ID.
           * @example char_002_amiya
           */
          charId: string
          /**
           * @description In-game skin ID.
           * @example char_002_amiya_1
           */
          skinId: string
        }
        /**
         * @description User's biography (签名).
         * @default 相关功能优化中，签名暂无法保存，请等待后续开放。（修改任务不受影响）
         */
        resume: string
        /**
         * @description Timestamp (in seconds) of the monthly subscription (月卡) end time. Unsure about the scenario where the user does not have a monthly subscription.
         * @example 1584537600
         */
        subscriptionEnd: number
        /**
         * Ap
         * @description User's AP (理智).
         */
        ap: {
          /**
           * @description Current AP (理智).
           * @example 28
           */
          current: number
          /**
           * @description Maximum AP (理智). The maximum AP depends on the user's level.
           * @example 135
           */
          max: number
          /**
           * @description Timestamp (in seconds) of the last AP (理智) addition time.
           * @example 1584537600
           */
          lastApAddTime: number
          /**
           * @description Timestamp (in seconds) of when the AP (理智) will be fully recovered to the current maximum AP (理智) of the user.
           * @example 1584537600
           */
          completeRecoveryTime: number
        }
        storeTs: number
        /**
         * @description Timestamp (in seconds) of the last online time.
         * @example 1584537600
         */
        lastOnlineTs: number
        /**
         * @description Total number of characters (干员) owned by the user. However, this value is currently always 0.
         * @example 0
         */
        charCnt: number
        /**
         * @description Total number of furniture (家具) owned by the user. However, this value is currently always 0.
         * @example 0
         */
        furnitureCnt: number
        /**
         * @description Total number of skins (服装) owned by the user. However, this value is currently always 0.
         * @example 0
         */
        skinCnt: number
      }
      /**
       * Medal
       * @description User's medal (蚀刻章) configuration on their profile page.
       */
      medal: {
        /**
         * @description CUSTOM means user's custom medal layout. Currently only CUSTOM is supported it seems.
         * @enum {string}
         */
        type: 'CUSTOM'
        template: string
        templateMedalList: unknown[]
        customMedalLayout: {
          /**
           * @description Medal ID.
           * @example medal_player_charnum_06
           */
          id: string
          /**
           * @description Position of the medal on the profile page. [x, y].
           * TODO: Find out the exact range of x and y, along with the pivot they represents.
           */
          pos: number[]
        }[]
        /** @description Total number of medals the user has already acquired. */
        total: number
      }
      /** @description User's assistant operators/support unit (助战干员) configuration. */
      assistChars: {
        /**
         * @description In-game Operator (干员) ID.
         * @example char_1028_texas2
         */
        charId: string
        /**
         * @description In-game Skin (干员服装) ID.
         * @example char_1028_texas2#2
         */
        skinId: string
        /** @description Operator's level (干员等级). Maximum value depends on the rarity of the operator. */
        level: number
        /**
         * @description Operator's current evolution phase (精英化等级). Maximum value depends on the rarity of the operator.
         * @enum {integer}
         */
        evolvePhase: 0 | 1 | 2
        /**
         * @description Operator's potential rank (潜能等级). Maximum value is 6. Initial value is 1 (right after the user acquired the operator).
         * @enum {integer}
         */
        potentialRank: 1 | 2 | 3 | 4 | 5 | 6
        /**
         * @description Operator's current skill (技能) ID that is configured as the assistance skill (助战技能).
         * @example skchr_texas2_3
         */
        skillId: string
        /** @description Operator's current skill (技能) level (技能等级). This level does not include the "specialize" level (专精等级). */
        mainSkillLvl: number
        /** @description Operator's current skill (技能) specialize level (专精等级). */
        specializeLevel: number
        /** @description Equipment (模组) the operator is currently equipped with. A `null` value means the operator is not equipped with any equipment. */
        equip:
          | {
              /** @description In-game Equipment (模组) ID. */
              id: string
              /** @description Equipment's level (模组等级). */
              level: number
            }
          | (Record<string, unknown> | null)
      }[]
      /** @description List of operators (干员) the user owns. */
      chars: {
        /**
         * @description In-game Operator (干员) ID.
         * @example char_1028_texas2
         */
        charId: string
        /**
         * @description In-game Skin (干员服装) ID.
         * @example char_1028_texas2#2
         */
        skinId: string
        /** @description Operator's level (干员等级). Maximum value depends on the rarity of the operator. */
        level: number
        /**
         * @description Operator's current evolution phase (精英化等级). Maximum value depends on the rarity of the operator.
         * @enum {integer}
         */
        evolvePhase: 0 | 1 | 2
        /**
         * @description Operator's potential rank (潜能等级). Maximum value is 6. Initial value is 1 (right after the user acquired the operator).
         * @enum {integer}
         */
        potentialRank: 1 | 2 | 3 | 4 | 5 | 6
        /** @description Operator's current skill (技能) level (技能等级). This level does not include the "specialize" level (专精等级). */
        mainSkillLvl: number
        /** @description All available skills (技能) of the operator. */
        skills: {
          /** @description In-game Skill (技能) ID. */
          id: string
          /** @description Operator's current skill (技能) specialize level (专精等级). */
          specializeLevel: number
        }[]
        /** @description All available equipments (模组) of the operator. */
        equip: {
          /** @description In-game Equipment (模组) ID. */
          id: string
          /** @description Equipment's level (模组等级). */
          level: number
        }[]
        /** @description Operator's favor (信赖值) percentage. Maximum value is 200. Initial value is 0 (right after the user acquired the operator). */
        favorPercent: number
        /**
         * @description Operator's default skill (默认技能) ID.
         * @example skchr_texas2_1
         */
        defaultSkillId: string
        /**
         * @description Timestamp (in seconds) when the user acquired the operator.
         * @example 1609459200
         */
        gainTime: number
        /**
         * @description Operator's default equipment (默认模组) ID.
         * @example equip_1028_texas2
         */
        defaultEquipId: string
      }[]
      /** @description List of skins (干员服装) the user owns. */
      skins: {
        /**
         * @description In-game Skin (服装) ID.
         * @example char_1028_texas2#2
         */
        id: string
        /**
         * @description Timestamp (in seconds) when the user acquired the skin.
         * @example 1609459200
         */
        ts: number
      }[]
      /**
       * Building
       * @description User's base (基建) status.
       */
      building: {
        /** @description List of operators (干员) that are currently tired (注意力涣散). TODO: Find out the item types in this array. */
        tiredChars: unknown[]
        /** @description Status of the Power Stations (发电站). */
        powers: {
          /**
           * @description In-game building slot (基建设施建造位) ID.
           * @example slot_26
           */
          slotId: string
          slotState?: number
          /** @description Building's level (基建设施等级). Regular buildings can be upgraded up to level 3. Dormitories (宿舍) can be upgraded up to level 5. */
          level: number
          /** @description List of operators (干员) that are currently located (进驻) in the building. */
          chars?: {
            /**
             * @description In-game Operator (干员) ID.
             * @example char_1028_texas2
             */
            charId: string
            /** @description Operator's current AP (注意力). */
            ap: number
            /** @description Timestamp (in seconds) when the operator's AP (注意力) was last added. */
            lastApAddTime: number
            /** @description Operator's index (位置). 0 means the operator is located at the left-most operator slot within the game. */
            index: number
            /**
             * Bubble
             * @description Operator (干员) bubble (信赖收取气泡) status.
             */
            bubble: {
              /** Assist */
              normal: {
                add: number
                ts: number
              }
              /** Assist */
              assist: {
                add: number
                ts: number
              }
            }
            /** @description Operator's current work time (工作时间) in minutes (分钟). */
            workTime: number
          }[]
          /** @description Building's comfort (舒适度). Only exists in dormitories (宿舍). */
          comfort?: number
        }[]
        /** @description Status of the Manufacture Stations (制造站). */
        manufactures: {
          /**
           * @description In-game building slot (基建设施建造位) ID.
           * @example slot_1
           */
          slotId: string
          /** @description Building's level (基建设施等级). */
          level: number
          chars: {
            /**
             * @description In-game Operator (干员) ID.
             * @example char_1028_texas2
             */
            charId: string
            /** @description Operator's current AP (注意力). */
            ap: number
            /** @description Timestamp (in seconds) when the operator's AP (注意力) was last added. */
            lastApAddTime: number
            /** @description Operator's index (位置). 0 means the operator is located at the left-most operator slot within the game. */
            index: number
            /**
             * Bubble
             * @description Operator (干员) bubble (信赖收取气泡) status.
             */
            bubble: {
              /** Assist */
              normal: {
                add: number
                ts: number
              }
              /** Assist */
              assist: {
                add: number
                ts: number
              }
            }
            /** @description Operator's current work time (工作时间) in minutes (分钟). */
            workTime: number
          }[]
          /**
           * @description Timestamp (in seconds) when the manufacture (制造站) will complete its current manufacture.
           * @example 1554105600
           */
          completeWorkTime: number
          /**
           * @description Timestamp (in seconds) when the manufacture (制造站) was last updated. TODO: Find out what this timestamp is used for.
           * @example 1554105600
           */
          lastUpdateTime: number
          /**
           * Format: integer
           * @description In-game manufacture formula (制造配方) ID.
           * @example 3
           */
          formulaId: string
          /** @description Manufacture's capacity (容量). */
          capacity: number
          /**
           * @description Manufacture's weight (负载)? TODO: Find out what this value is used for.
           * @example 0
           */
          weight: number
          /**
           * @description Manufacture's complete (完成) status? TODO: Find out what this value is used for.
           * @example 0
           */
          complete: number
          /**
           * @description Manufacture's remain (剩余) status? TODO: Find out what this value is used for.
           * @example 99
           */
          remain: number
          /** @description Manufacture's speed (速度) multiplier. */
          speed: number
        }[]
        /** @description Status of the Trading Stations (贸易站). */
        tradings: {
          /**
           * @description In-game building slot (基建设施建造位) ID.
           * @example slot_1
           */
          slotId: string
          /** @description Building's level (基建设施等级). */
          level: number
          /** @description List of operators (干员) that are currently located (进驻) in the building. */
          chars: {
            /**
             * @description In-game Operator (干员) ID.
             * @example char_1028_texas2
             */
            charId: string
            /** @description Operator's current AP (注意力). */
            ap: number
            /** @description Timestamp (in seconds) when the operator's AP (注意力) was last added. */
            lastApAddTime: number
            /** @description Operator's index (位置). 0 means the operator is located at the left-most operator slot within the game. */
            index: number
            /**
             * Bubble
             * @description Operator (干员) bubble (信赖收取气泡) status.
             */
            bubble: {
              /** Assist */
              normal: {
                add: number
                ts: number
              }
              /** Assist */
              assist: {
                add: number
                ts: number
              }
            }
            /** @description Operator's current work time (工作时间) in minutes (分钟). */
            workTime: number
          }[]
          /**
           * @description Timestamp (in seconds) when the trading (贸易站) will complete its current trade.
           * @example 1554105600
           */
          completeWorkTime: number
          /**
           * @description Timestamp (in seconds) when the trading (贸易站) was last updated. TODO: Find out what this timestamp is used for.
           * @example 1554105600
           */
          lastUpdateTime: number
          /**
           * Strategy
           * @description Trading (贸易) type. TODO: add more types.
           * @enum {string}
           */
          strategy: 'O_GOLD'
          /** @description List of stocks (库存) the trading (贸易站) currently has. */
          stock: {
            /** Format: integer */
            instId: number
            /**
             * Strategy
             * @description Trading (贸易) type. TODO: add more types.
             * @enum {string}
             */
            type: 'O_GOLD'
            /** @description List of items needed to deliver (交付) in order to get the gain (收益). These items will be consumed when the delivery is complete. */
            delivery: {
              /**
               * Format: integer
               * @description In-game item (物品) ID.
               */
              id: string
              /** @description Amount of the item (物品). */
              count: number
              /**
               * ItemType
               * @description In-game item (物品) type. TODO: add more types.
               * @enum {string}
               */
              type: 'MATERIAL' | 'GOLD'
            }[]
            /**
             * StockItem
             * @description Gain (收益) the user will get when the delivery is complete.
             */
            gain: {
              /**
               * Format: integer
               * @description In-game item (物品) ID.
               */
              id: string
              /** @description Amount of the item (物品). */
              count: number
              /**
               * ItemType
               * @description In-game item (物品) type. TODO: add more types.
               * @enum {string}
               */
              type: 'MATERIAL' | 'GOLD'
            }
            /** @description TODO: Find out what this value is used for. */
            isViolated: boolean
          }[]
          /** @description Trading's stock limit (库存上限). */
          stockLimit: number
        }[]
        /** @description Status of the Dormitories (宿舍). */
        dormitories: {
          /**
           * @description In-game building slot (基建设施建造位) ID.
           * @example slot_26
           */
          slotId: string
          slotState?: number
          /** @description Building's level (基建设施等级). Regular buildings can be upgraded up to level 3. Dormitories (宿舍) can be upgraded up to level 5. */
          level: number
          /** @description List of operators (干员) that are currently located (进驻) in the building. */
          chars?: {
            /**
             * @description In-game Operator (干员) ID.
             * @example char_1028_texas2
             */
            charId: string
            /** @description Operator's current AP (注意力). */
            ap: number
            /** @description Timestamp (in seconds) when the operator's AP (注意力) was last added. */
            lastApAddTime: number
            /** @description Operator's index (位置). 0 means the operator is located at the left-most operator slot within the game. */
            index: number
            /**
             * Bubble
             * @description Operator (干员) bubble (信赖收取气泡) status.
             */
            bubble: {
              /** Assist */
              normal: {
                add: number
                ts: number
              }
              /** Assist */
              assist: {
                add: number
                ts: number
              }
            }
            /** @description Operator's current work time (工作时间) in minutes (分钟). */
            workTime: number
          }[]
          /** @description Building's comfort (舒适度). Only exists in dormitories (宿舍). */
          comfort?: number
        }[]
        /**
         * Meeting
         * @description Status of the Meeting Room (会客室).
         */
        meeting: {
          /**
           * @description In-game building slot (基建设施建造位) ID.
           * @example slot_1
           */
          slotId: string
          /** @description Building's level (基建设施等级). */
          level: number
          /** @description List of operators (干员) that are currently located (进驻) in the building. */
          chars: {
            /**
             * @description In-game Operator (干员) ID.
             * @example char_1028_texas2
             */
            charId: string
            /** @description Operator's current AP (注意力). */
            ap: number
            /** @description Timestamp (in seconds) when the operator's AP (注意力) was last added. */
            lastApAddTime: number
            /** @description Operator's index (位置). 0 means the operator is located at the left-most operator slot within the game. */
            index: number
            /**
             * Bubble
             * @description Operator (干员) bubble (信赖收取气泡) status.
             */
            bubble: {
              /** Assist */
              normal: {
                add: number
                ts: number
              }
              /** Assist */
              assist: {
                add: number
                ts: number
              }
            }
            /** @description Operator's current work time (工作时间) in minutes (分钟). */
            workTime: number
          }[]
          /**
           * Clue
           * @description Clue (线索) status.
           */
          clue: {
            /** @description Amount of clues (线索) the user currently owns. */
            own: number
            /** @description Amount of clues (线索) the user has received. */
            received: number
            /** @description Whether the user has received the daily clue (线索) reward. */
            dailyReward: boolean
            /** @description Amount of clues (线索) that is available for the user to be received. */
            needReceive: number
            /** @description List of clues (线索) the user currently has on the board (线索槽). TODO: add more types. */
            board: ('RHINE' | 'PENGUIN' | 'BLACKSTEEL' | 'RHODES' | 'GLASGOW')[]
            /**
             * @description Whether the user is currently in sharing (线索交流开启中) status.
             * @example false
             */
            sharing: boolean
            /**
             * @description Timestamp (in seconds) when the sharing (线索交流) will complete.
             * @example 1554105600
             */
            shareCompleteTime: number
          }
          /**
           * @description Timestamp (in seconds) when the meeting (会客室) was last updated. TODO: Find out what this timestamp is used for.
           * @example 1554105600
           */
          lastUpdateTime: number
          /**
           * @description Timestamp (in seconds) when the operators (干员) in the meeting (会客室) will become tired (注意力涣散).
           * @example 1554105600
           */
          completeWorkTime: number
        }
        /** Hire */
        hire: {
          slotId: string
          level: number
          chars: {
            /**
             * @description In-game Operator (干员) ID.
             * @example char_1028_texas2
             */
            charId: string
            /** @description Operator's current AP (注意力). */
            ap: number
            /** @description Timestamp (in seconds) when the operator's AP (注意力) was last added. */
            lastApAddTime: number
            /** @description Operator's index (位置). 0 means the operator is located at the left-most operator slot within the game. */
            index: number
            /**
             * Bubble
             * @description Operator (干员) bubble (信赖收取气泡) status.
             */
            bubble: {
              /** Assist */
              normal: {
                add: number
                ts: number
              }
              /** Assist */
              assist: {
                add: number
                ts: number
              }
            }
            /** @description Operator's current work time (工作时间) in minutes (分钟). */
            workTime: number
          }[]
          state: number
          refreshCount: number
          completeWorkTime: number
          slotState: number
        }
        /** Training */
        training: {
          slotId: string
          level: number
          /** Traine */
          trainee: {
            charId: string
            targetSkill?: number
            ap: number
            lastApAddTime: number
          }
          /** Traine */
          trainer: {
            charId: string
            targetSkill?: number
            ap: number
            lastApAddTime: number
          }
          remainPoint: number
          speed: number
          lastUpdateTime: number
          remainSecs: number
          slotState: number
        }
        /** Labor */
        labor: {
          maxValue: number
          value: number
          lastUpdateTime: number
          remainSecs: number
        }
        /** Furniture */
        furniture: {
          total: number
        }
        elevators: {
          /**
           * @description In-game building slot (基建设施建造位) ID.
           * @example slot_26
           */
          slotId: string
          slotState?: number
          /** @description Building's level (基建设施等级). Regular buildings can be upgraded up to level 3. Dormitories (宿舍) can be upgraded up to level 5. */
          level: number
          /** @description List of operators (干员) that are currently located (进驻) in the building. */
          chars?: {
            /**
             * @description In-game Operator (干员) ID.
             * @example char_1028_texas2
             */
            charId: string
            /** @description Operator's current AP (注意力). */
            ap: number
            /** @description Timestamp (in seconds) when the operator's AP (注意力) was last added. */
            lastApAddTime: number
            /** @description Operator's index (位置). 0 means the operator is located at the left-most operator slot within the game. */
            index: number
            /**
             * Bubble
             * @description Operator (干员) bubble (信赖收取气泡) status.
             */
            bubble: {
              /** Assist */
              normal: {
                add: number
                ts: number
              }
              /** Assist */
              assist: {
                add: number
                ts: number
              }
            }
            /** @description Operator's current work time (工作时间) in minutes (分钟). */
            workTime: number
          }[]
          /** @description Building's comfort (舒适度). Only exists in dormitories (宿舍). */
          comfort?: number
        }[]
        corridors: {
          /**
           * @description In-game building slot (基建设施建造位) ID.
           * @example slot_26
           */
          slotId: string
          slotState?: number
          /** @description Building's level (基建设施等级). Regular buildings can be upgraded up to level 3. Dormitories (宿舍) can be upgraded up to level 5. */
          level: number
          /** @description List of operators (干员) that are currently located (进驻) in the building. */
          chars?: {
            /**
             * @description In-game Operator (干员) ID.
             * @example char_1028_texas2
             */
            charId: string
            /** @description Operator's current AP (注意力). */
            ap: number
            /** @description Timestamp (in seconds) when the operator's AP (注意力) was last added. */
            lastApAddTime: number
            /** @description Operator's index (位置). 0 means the operator is located at the left-most operator slot within the game. */
            index: number
            /**
             * Bubble
             * @description Operator (干员) bubble (信赖收取气泡) status.
             */
            bubble: {
              /** Assist */
              normal: {
                add: number
                ts: number
              }
              /** Assist */
              assist: {
                add: number
                ts: number
              }
            }
            /** @description Operator's current work time (工作时间) in minutes (分钟). */
            workTime: number
          }[]
          /** @description Building's comfort (舒适度). Only exists in dormitories (宿舍). */
          comfort?: number
        }[]
        /** Control */
        control: {
          /**
           * @description In-game building slot (基建设施建造位) ID.
           * @example slot_26
           */
          slotId: string
          slotState?: number
          /** @description Building's level (基建设施等级). Regular buildings can be upgraded up to level 3. Dormitories (宿舍) can be upgraded up to level 5. */
          level: number
          /** @description List of operators (干员) that are currently located (进驻) in the building. */
          chars?: {
            /**
             * @description In-game Operator (干员) ID.
             * @example char_1028_texas2
             */
            charId: string
            /** @description Operator's current AP (注意力). */
            ap: number
            /** @description Timestamp (in seconds) when the operator's AP (注意力) was last added. */
            lastApAddTime: number
            /** @description Operator's index (位置). 0 means the operator is located at the left-most operator slot within the game. */
            index: number
            /**
             * Bubble
             * @description Operator (干员) bubble (信赖收取气泡) status.
             */
            bubble: {
              /** Assist */
              normal: {
                add: number
                ts: number
              }
              /** Assist */
              assist: {
                add: number
                ts: number
              }
            }
            /** @description Operator's current work time (工作时间) in minutes (分钟). */
            workTime: number
          }[]
          /** @description Building's comfort (舒适度). Only exists in dormitories (宿舍). */
          comfort?: number
        }
      }
      /** @description User's current recruit (公开招募) status. */
      recruit: {
        /**
         * @description Timestamp (in seconds) when the recruit (公开招募) started.
         * @example 1554105600
         */
        startTs: number
        /**
         * @description Timestamp (in seconds) when the recruit (公开招募) will finish.
         * @example 1554105600
         */
        finishTs: number
        /** @description Duration (持续时间) of the recruit (公开招募) in seconds. */
        duration: number
        selectTags: unknown[]
        state: number
      }[]
      /** Campaign */
      campaign: {
        records: {
          campaignId: string
          maxKills: number
        }[]
        /** DailyClass */
        reward: {
          current: number
          total: number
        }
      }
      /** Tower */
      tower: {
        records: {
          towerId: string
          best: number
          hasHard: boolean
          stageNum: number
          unlockHard: boolean
          hardBest: number
        }[]
        /** TowerReward */
        reward: {
          /** DailyClass */
          higherItem: {
            current: number
            total: number
          }
          /** DailyClass */
          lowerItem: {
            current: number
            total: number
          }
          termTs: number
        }
      }
      /** Rogue */
      rogue: {
        records: {
          rogueId: string
          clearTime: number
          relicCnt: number
          /** Bank */
          bank: {
            current: number
            record: number
          }
          /** DailyClass */
          mission: {
            current: number
            total: number
          }
        }[]
      }
      /** Routine */
      routine: {
        /** DailyClass */
        daily: {
          current: number
          total: number
        }
        /** DailyClass */
        weekly: {
          current: number
          total: number
        }
      }
      activity: {
        actId: string
        actReplicaId: string
        type: string
        zones: {
          zoneId: string
          zoneReplicaId: string
          clearedStage: number
          totalStage: number
          stageStatus: {
            stageId: string
            completed: boolean
          }[]
        }[]
      }[]
      /** CharInfoMap */
      charInfoMap: {
        id: string
        name: string
        nationId: string
        /**
         * GroupID
         * @enum {string}
         */
        groupId:
          | ''
          | 'lgd'
          | 'elite'
          | 'penguin'
          | 'dublinn'
          | 'abyssal'
          | 'rhine'
          | 'blacksteel'
          | 'glasgow'
          | 'babel'
          | 'sweep'
          | 'karlan'
          | 'sui'
          | 'siesta'
          | 'pinus'
        displayNumber: string
        rarity: number
        /**
         * Profession
         * @enum {string}
         */
        profession: 'CASTER' | 'MEDIC' | 'WARRIOR' | 'SUPPORT' | 'SNIPER' | 'SPECIAL' | 'PIONEER' | 'TANK'
        subProfessionId: string
      }
      /** SkinInfoMap */
      skinInfoMap: {
        id: string
        name: string
        brandId: string
        brandName: string
        brandCapitalName: string
        illustId: string
        dynIllustId: string
        avatarId: string
        portraitId: string
        sortId: number
        /**
         * DisplayTagID
         * @enum {string}
         */
        displayTagId: '活动获得' | '设定集' | '' | '联动获得' | '特典获得' | '赛季服饰' | '集成战略'
        skinGroupId: string
      }
      /** StageInfoMap */
      stageInfoMap: {
        id: string
        code: string
        name: string
      }
      /** ActivityInfoMap */
      activityInfoMap: {
        id: string
        name: string
        startTime: number
        endTime: number
        rewardEndTime: number
        isReplicate: boolean
        /**
         * ActivityInfoMapType
         * @enum {string}
         */
        type: 'SIDESTORY' | 'MINISTORY' | '' | 'BRANCHLINE'
      }
      /** CampaignZoneInfoMap */
      zoneInfoMap: {
        id: string
        name: string
      }
      /** TowerInfoMap */
      towerInfoMap: {
        id: string
        name: string
        subName: string
        hasHard: boolean
        stageNum: number
      }
      /** RogueInfoMap */
      rogueInfoMap: {
        /** Rogue1_Class */
        rogue_1: {
          id: string
          name: string
          sort: number
        }
        /** Rogue1_Class */
        rogue_2: {
          id: string
          name: string
          sort: number
        }
        /** Rogue1_Class */
        rogue_3: {
          id: string
          name: string
          sort: number
        }
      }
      /** CampaignInfoMap */
      campaignInfoMap: {
        id: string
        name: string
        campaignZoneId: string
      }
      /** MedalInfoMap */
      medalInfoMap: {
        /** CampaignZoneInfoMap */
        medal_activity_6d5_01?: {
          id: string
          name: string
        }
        /** CampaignZoneInfoMap */
        medal_player_charnum_06?: {
          id: string
          name: string
        }
        /** CampaignZoneInfoMap */
        medal_player_joingame_03?: {
          id: string
          name: string
        }
        /** CampaignZoneInfoMap */
        medal_player_recruitcount_08?: {
          id: string
          name: string
        }
        [key: string]: unknown
      }
      /** CampaignZoneInfoMap */
      campaignZoneInfoMap: {
        id: string
        name: string
      }
      /** EquipmentInfoMap */
      equipmentInfoMap: {
        id: string
        name: string
        desc: string
        typeIcon: string
        typeName1: string
        /**
         * ShiningColor
         * @enum {string}
         */
        shiningColor: 'grey' | 'red' | 'yellow' | 'blue' | 'green'
        /**
         * TypeName2
         * @enum {string}
         */
        typeName2?: 'X' | 'Y'
      }
      /** ManufactureFormulaInfoMap */
      manufactureFormulaInfoMap: {
        /** Format: integer */
        id: string
        /** Format: integer */
        itemId: string
        count: number
        weight: number
        costs: unknown[]
        costPoint: number
      }
      charAssets: unknown[]
      skinAssets: unknown[]
    }
    GetGamePlayerBindingResponseData: {
      list: {
        /** @example arknights */
        appCode: string
        /** @example 明日方舟 */
        appName: string
        bindingList: {
          /**
           * Format: integer
           * @example 10000001
           */
          uid: string
          /** @example true */
          isOfficial: boolean
          /** @example true */
          isDefault: boolean
          /**
           * Format: integer
           * @example 1
           */
          channelMasterId: string
          /** @example 官服 */
          channelName: string
          /** @example Amiya#1234 */
          nickName: string
          /** @example false */
          isDelete: boolean
        }[]
      }[]
    }
    GetGamesResponseData: {
      list: {
        /** Game */
        game: {
          gameId: number
          name: string
          /** Format: uri */
          iconUrl: string
          /** Format: uri */
          backgroundUrl: string
        }
        cates: {
          id: number
          gameId: number
          name: string
          description: string
          /** Icon */
          nameIcon: {
            id?: string
            url: string
            width: number
            height: number
            size: number
            /**
             * Format
             * @enum {string}
             */
            format: '' | 'jpg' | 'png'
          }
          /** Icon */
          icon: {
            id?: string
            url: string
            width: number
            height: number
            size: number
            /**
             * Format
             * @enum {string}
             */
            format: '' | 'jpg' | 'png'
          }
          kind: number
          allowedViewKinds: number[]
          position: number
          bannerOnOff: number
          headlineOnOff: number
          billboardOnOff: number
          status: number
          startAtTs: number
          createdAtTs: number
          updatedAtTs: number
        }[]
        quickaccesses: {
          id: number
          gameId: number
          name: string
          /** Icon */
          icon: {
            id?: string
            url: string
            width: number
            height: number
            size: number
            /**
             * Format
             * @enum {string}
             */
            format: '' | 'jpg' | 'png'
          }
          link: string
          position: number
          status: number
          startAtTs: number
          createdAtTs: number
          updatedAtTs: number
        }[]
        /** Tag */
        tag: {
          id: number
          name: string
          description: string
          status: number
          /** Format: uri */
          cover: string
          publishAtTs: number
          createdAtTs: number
          updatedAtTs: number
        }
      }[]
    }
    GenerateCredByCodeRequestData: {
      /**
       * @description （未知）疑似登录类型
       * @enum {number}
       */
      kind: 1
      /**
       * @description 鹰角网络通行证 OAuth2 授权码（Authorization Code）。注：提供的例子已经过脱敏处理
       * @example AAAALXgBLPoCAAAAZT0lzUnmq2020AAADiPjJzaWBmsoYIojpuCgAAANNpmsQSFFLlEfpJDCq6Mka/PtEf//AlIARhPVo4iPePgtFCJUqjNTN9W6egJdmjTdohmA3h1zegtDce8a13dZ73ZkS+GIlLre2g0fBqF2hXtQhxnwKmcvIpk=
       */
      code: string
      [key: string]: unknown
    }
    GenerateCredByCodeResponseData: {
      /**
       * @description 森空岛用户登录凭证
       * @example ##REDACTED##
       */
      cred: string
      /**
       * @description 森空岛用户 ID
       * @example 101000
       */
      userId: string
      [key: string]: unknown
    }
  }
  responses: {}
  parameters: {}
  requestBodies: {}
  headers: {
    /** @description The user's credentials */
    cred: string
  }
  pathItems: never
}

export type external = Record<string, never>

export interface operations {
  /** Get Current Available Games */
  GetGames: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /**
             * @description Business-level response code
             * @example 0
             */
            code: number
            /**
             * @description Business-level response message
             * @example OK
             */
            message: string
            data: components['schemas']['GetGamesResponseData']
          }
        }
      }
    }
  }
  /** Get Player Detailed Info */
  GetGamePlayerInfo: {
    parameters: {
      query: {
        /** @description The *character* ID (角色 ID), different from the user ID and is different for each "game server" combination. */
        uid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /**
             * @description Business-level response code
             * @example 0
             */
            code: number
            /**
             * @description Business-level response message
             * @example OK
             */
            message: string
            data: components['schemas']['GetGamePlayerInfoResponseData']
          }
        }
      }
      /** @description Unauthorized */
      401: {
        content: {
          'application/json': {
            /**
             * @description Error code
             * @example 10001
             */
            code: number
            /**
             * @description Error message
             * @example 用户未登录
             */
            message: string
          }
        }
      }
    }
  }
  /**
   * Get Player Binding
   * @description Get the player's binding (Skland ID <-> Game ID) info
   */
  GetGamePlayerBinding: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            /**
             * @description Business-level response code
             * @example 0
             */
            code: number
            /**
             * @description Business-level response message
             * @example OK
             */
            message: string
            data: components['schemas']['GetGamePlayerBindingResponseData']
          }
        }
      }
      /** @description Unauthorized */
      401: {
        content: {
          'application/json': {
            /**
             * @description Error code
             * @example 10001
             */
            code: number
            /**
             * @description Error message
             * @example 用户未登录
             */
            message: string
          }
        }
      }
    }
  }
  /**
   * 通过鹰角网络通行证 OAuth2 授权码（Authorization Code）生成森空岛用户的登录凭证
   * @description 仅有获得内测资格的用户才可以生成登录凭证。如果该用户没有获得内测资格，则会返回 403 Forbidden。
   */
  GenerateCredByCode: {
    requestBody: {
      content: {
        'application/json': components['schemas']['GenerateCredByCodeRequestData']
      }
    }
    responses: {
      /** @description 成功 */
      200: {
        content: {
          'application/json': {
            /**
             * @description Business-level response code
             * @example 0
             */
            code: number
            /**
             * @description Business-level response message
             * @example OK
             */
            message: string
            data: components['schemas']['GenerateCredByCodeResponseData']
          }
        }
      }
      /** @description 鹰角授权Code无效 */
      401: {
        content: {
          'application/json': {
            /**
             * @description 错误代码
             * @example 10001
             */
            code: number
            /**
             * @description 错误信息
             * @example 鹰角授权Code无效
             */
            message: string
          }
        }
      }
      /** @description 用户不在授权白名单内 */
      403: {
        content: {
          'application/json': {
            /**
             * @description 错误代码
             * @example 1
             */
            code: number
            /**
             * @description 错误信息
             * @example 用户不在授权白名单内
             */
            message: string
          }
        }
      }
    }
  }
}
